# -*- coding: utf-8 -*-
"""factorielle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-6-9wP7-cAi4w5-Fc-CHMsYnS_u7vMSO

#Examen : Djambala GORY

##b.Fonction Factorielle: Avec n pour paramètre d'entrée
"""

# b. Fonction factorielle :
def factorielle(n):
   if n == 0: # Traitement du cas où n = 0
      return 1
   else:
      F = 1
      for k in range(2,n+1): # Itération sur les valeurs de 1 à n afin d'appliquer la multiplication
         F = F * k
      return F

# Exemple
factorielle(5) # Valeur retournée est 120<=>5!