# -*- coding: utf-8 -*-
"""Fibonacci.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-1IZ1WcrpA5u8l2nKvAGYc-xqmUV-H5v

#Examen : Djambala GORY

##c.Suite de Fibonnaci: Avec nbr le nombre saisi par l'utilisateur.
"""

nbr=int(input("Entrez un nombre: "))
# On définit les deux prémières valeurs de la serie de fibonacci.
n1 = 0
n2 = 1
print("\n la suite fibonacci est :")
print(n1, ",", n2, end=", ")
for i in range(2, nbr):
  next = n1 + n2
  print(next, end=", ")
  n1 = n2
  n2 = next