# -*- coding: utf-8 -*-
"""polynome.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rgLEc9fwJYCICwWquzAQKThqcpeqX5fR

#Examen : Djambala GORY

##a.Fonction Polynome: Avec l'inconnu x pour paramètre d'entrée.
"""

# a. Implémentation de la fonction : f(x)=x^3-1.5x^2-6x+5
def Polynome(x):
  y=x**3-1.5*x**2-6*x+5
  return y

# Exemple fonction Polynome :
Polynome(5) # retourne 62.5